spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/meet_mate?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:CmileTally2db}
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 9009
  error:
    include-message: always