server:
  port: 9009
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  main:
    allow-circular-references: true
  application:
    name: meet-mate
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/meet_mate?useSSL=false
    username: root
    password: root@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher