spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meet_mate?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 9009
  error:
    include-message: always